import type { Pathology } from './types'

export const PATHOLOGIES: Pathology[] = [
  // SPECIFICATION
  {
    code: 'P-001',
    name: 'Specification Absence',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'CRITICAL',
    description: 'No persistent machine-readable system description. Code is the only source of truth. AI fills gaps with guesses that change every session.',
    scoringRules: {
      signals: [
        { signal: 'no_spec_document', weight: 0.4, source_bonus: { spec: 0.1 } },
        { signal: 'no_spec_index', weight: 0.3, source_bonus: { claudeMd: 0.15 } },
        { signal: 'no_navigation_root', weight: 0.3, source_bonus: { claudeMd: 0.15 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-002',
    name: 'Specification Debt',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'HIGH',
    description: 'Some documentation exists, but it is incomplete, fragmented, or not usable as a machine-routable source of truth. Teams have artifacts, but AI still cannot reliably derive intent from them.',
    scoringRules: {
      signals: [
        { signal: 'no_spec_document', weight: 0.3, source_bonus: { spec: 0.1 } },
        { signal: 'no_defended_spec', weight: 0.25, source_bonus: { spec: 0.1 } },
        { signal: 'no_spec_index', weight: 0.25, source_bonus: { claudeMd: 0.15 } },
        { signal: 'no_adr_files', weight: 0.2, source_bonus: { adr: 0.15 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-003',
    name: 'Spec-Last Development',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'CRITICAL',
    description: 'Code written before spec. Spec written after (if ever). No specification-first discipline. AI accelerates this collapse into vibe coding.',
    scoringRules: {
      signals: [
        { signal: 'spec_last_workflow', weight: 0.45, source_bonus: { survey: 0.05 } },
        { signal: 'no_spec_document', weight: 0.35, source_bonus: { spec: 0.1 } },
        { signal: 'no_session_protocol', weight: 0.2, source_bonus: { claudeMd: 0.15, survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-004',
    name: 'Stale Specification',
    gsProperty: 'AUDITABLE',
    severity: 'HIGH',
    description: 'Spec created once, never updated. Code diverges. AI reading stale docs produces stale code. Documentation drift becomes structural.',
    scoringRules: {
      signals: [
        { signal: 'no_spec_document', weight: 0.4, source_bonus: { spec: 0.1 } },
        { signal: 'no_adr_files', weight: 0.3, source_bonus: { adr: 0.15 } },
        { signal: 'no_session_protocol', weight: 0.3, source_bonus: { claudeMd: 0.15, survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // AI_NAVIGATION
  {
    code: 'P-005',
    name: 'Architectural Drift',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'CRITICAL',
    description: 'AI sessions produce globally incoherent output — locally valid but boundary-violating. No navigation root, no layer enforcement. Absorbs Implicit Architecture.',
    scoringRules: {
      signals: [
        { signal: 'no_navigation_root', weight: 0.25, source_bonus: { claudeMd: 0.15 } },
        { signal: 'no_layer_enforcement', weight: 0.3 },
        { signal: 'no_adr_files', weight: 0.2, source_bonus: { adr: 0.15 } },
        { signal: 'inconsistent_naming', weight: 0.25, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-006',
    name: 'Session Amnesia',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'HIGH',
    description: 'No continuity between AI sessions. Each session starts from scratch producing contradictory decisions. Absorbs AI Output Drift (same root cause).',
    scoringRules: {
      signals: [
        { signal: 'no_navigation_root', weight: 0.35, source_bonus: { claudeMd: 0.15 } },
        { signal: 'no_session_protocol', weight: 0.35, source_bonus: { claudeMd: 0.15, survey: 0.05 } },
        { signal: 'no_adr_files', weight: 0.3, source_bonus: { adr: 0.15 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-007',
    name: 'Navigation Blindness',
    gsProperty: 'BOUNDED',
    severity: 'HIGH',
    description: 'No routing mechanism for AI to find relevant context. CLAUDE.md missing. AI loads random files, wastes context on irrelevant code.',
    scoringRules: {
      signals: [
        { signal: 'no_navigation_root', weight: 0.4, source_bonus: { claudeMd: 0.15 } },
        { signal: 'no_spec_index', weight: 0.35, source_bonus: { claudeMd: 0.15 } },
        { signal: 'no_claude_md', weight: 0.25, source_bonus: { claudeMd: 0.15 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-008',
    name: 'Silent Assumption',
    gsProperty: 'DEFENDED',
    severity: 'HIGH',
    description: 'AI resolves ambiguous decisions silently without flagging them. No forbidden patterns catalog. No spec guard rails.',
    scoringRules: {
      signals: [
        { signal: 'no_forbidden_patterns', weight: 0.4 },
        { signal: 'no_navigation_root', weight: 0.3, source_bonus: { claudeMd: 0.15 } },
        { signal: 'no_defended_spec', weight: 0.3, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // ARCHITECTURE
  {
    code: 'P-009',
    name: 'Layer & Dependency Violation',
    gsProperty: 'COMPOSABLE',
    severity: 'HIGH',
    description: 'DB calls from controllers. Circular imports. No layer enforcement. Changing one module breaks three others. No port/adapter isolation.',
    scoringRules: {
      signals: [
        { signal: 'no_layer_enforcement', weight: 0.35 },
        { signal: 'no_dependency_rules', weight: 0.3 },
        { signal: 'no_interface_definitions', weight: 0.35 },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-010',
    name: 'Code Duplication Creep',
    gsProperty: 'COMPOSABLE',
    severity: 'MEDIUM',
    description: 'Same logic copy-pasted 3+ times. No shared abstraction. AI generates new copies rather than reusing existing utilities.',
    scoringRules: {
      signals: [
        { signal: 'no_duplication_gate', weight: 0.5 },
        { signal: 'no_shared_utilities', weight: 0.3 },
        { signal: 'no_layer_enforcement', weight: 0.2 },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-011',
    name: 'Dead Code Accumulation',
    gsProperty: 'BOUNDED',
    severity: 'LOW',
    description: 'Unused files, exports, and variables accumulate. No dead code detection. Fear of deleting AI-generated code.',
    scoringRules: {
      signals: [
        { signal: 'no_dead_code_gate', weight: 0.5 },
        { signal: 'no_dependency_rules', weight: 0.5 },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-012',
    name: 'Ghost Failure Cascade',
    gsProperty: 'EXECUTABLE',
    severity: 'HIGH',
    description: 'Infrastructure misconfigs produce failures that look like code bugs. No deployment docs. Prod differs from dev in unknown ways.',
    scoringRules: {
      signals: [
        { signal: 'infra_misconfig_signals', weight: 0.5, source_bonus: { survey: 0.05 } },
        { signal: 'no_deployment_doc', weight: 0.5, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // KNOWLEDGE
  {
    code: 'P-013',
    name: 'Bus Factor',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'CRITICAL',
    description: 'Critical knowledge concentrated in 1-2 people. If they leave the team cannot maintain key systems. No CODEOWNERS, no onboarding docs.',
    scoringRules: {
      signals: [
        { signal: 'bus_factor_risk', weight: 0.5, source_bonus: { survey: 0.05 } },
        { signal: 'no_onboarding_docs', weight: 0.3, source_bonus: { spec: 0.1, survey: 0.05 } },
        { signal: 'no_adr_files', weight: 0.2, source_bonus: { adr: 0.15 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-014',
    name: 'Junior Developer Death Spiral',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'CRITICAL',
    description: 'Entry-level hiring declining, no talent pipeline. Seniors overloaded. AI accelerates this by making junior skill development harder to quantify.',
    scoringRules: {
      signals: [
        { signal: 'bus_factor_risk', weight: 0.4, source_bonus: { survey: 0.05 } },
        { signal: 'skill_atrophy_signs', weight: 0.35, source_bonus: { survey: 0.05 } },
        { signal: 'no_onboarding_docs', weight: 0.25, source_bonus: { spec: 0.1, survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-015',
    name: 'Technical Debt Blindness',
    gsProperty: 'AUDITABLE',
    severity: 'HIGH',
    description: 'No tech debt tracking. Never prioritized in sprints. Growing incident rate. AI-generated code adds debt faster than manual tracking can capture.',
    scoringRules: {
      signals: [
        { signal: 'no_tech_debt_tracking', weight: 0.6, source_bonus: { survey: 0.05 } },
        { signal: 'no_adr_files', weight: 0.4, source_bonus: { adr: 0.15 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-016',
    name: 'Rationale Loss',
    gsProperty: 'AUDITABLE',
    severity: 'MEDIUM',
    description: 'No ADR files. Commit messages are "fix bug". No decision log. Architectural choices undocumented. AI cannot reference past decisions.',
    scoringRules: {
      signals: [
        { signal: 'no_adr_files', weight: 0.5, source_bonus: { adr: 0.15 } },
        { signal: 'no_conventional_commits', weight: 0.3, source_bonus: { survey: 0.05 } },
        { signal: 'no_decision_log', weight: 0.2, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-017',
    name: 'Naming Anarchy',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'MEDIUM',
    description: 'Same concept has 3+ names. No domain glossary. AI generates inconsistent terminology. Vocabulary drift between API, DB, and docs.',
    scoringRules: {
      signals: [
        { signal: 'no_domain_vocabulary', weight: 0.5, source_bonus: { spec: 0.1 } },
        { signal: 'inconsistent_naming', weight: 0.5, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-018',
    name: 'Context Fragmentation',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'MEDIUM',
    description: 'Project knowledge scattered across chat, heads, Slack, and tickets. No single source of truth. AI cannot reconstruct full context.',
    scoringRules: {
      signals: [
        { signal: 'no_team_ai_playbook', weight: 0.4, source_bonus: { survey: 0.05 } },
        { signal: 'no_navigation_root', weight: 0.35, source_bonus: { claudeMd: 0.15 } },
        { signal: 'no_session_protocol', weight: 0.25, source_bonus: { claudeMd: 0.15, survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // TESTING
  {
    code: 'P-019',
    name: 'Verification Gap',
    gsProperty: 'VERIFIABLE',
    severity: 'HIGH',
    description: 'No test coverage gate. Coverage <40%. No mutation testing. "It compiles" treated as done.',
    scoringRules: {
      signals: [
        { signal: 'no_test_files', weight: 0.35, source_bonus: { testFile: 0.1 } },
        { signal: 'no_coverage_config', weight: 0.35, source_bonus: { testFile: 0.1 } },
        { signal: 'no_ci_gate', weight: 0.3 },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-020',
    name: 'Test Surface Blindness',
    gsProperty: 'VERIFIABLE',
    severity: 'HIGH',
    description: 'Tests cover execution paths but miss behavioral contracts. No E2E or contract tests. Coverage metrics mask quality.',
    scoringRules: {
      signals: [
        { signal: 'no_contract_tests', weight: 0.35, source_bonus: { testFile: 0.1 } },
        { signal: 'no_e2e_tests', weight: 0.35, source_bonus: { testFile: 0.1 } },
        { signal: 'tests_not_behavioral', weight: 0.3, source_bonus: { testFile: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-021',
    name: 'Test Theater',
    gsProperty: 'VERIFIABLE',
    severity: 'HIGH',
    description: 'Tests exist but do not catch bugs. High coverage, zero mutation score. AI writes tests to pass, not to verify.',
    scoringRules: {
      signals: [
        { signal: 'tests_not_behavioral', weight: 0.45, source_bonus: { testFile: 0.1 } },
        { signal: 'no_coverage_config', weight: 0.35, source_bonus: { testFile: 0.1 } },
        { signal: 'no_contract_tests', weight: 0.2, source_bonus: { testFile: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-022',
    name: 'Implicit Contract Syndrome',
    gsProperty: 'COMPOSABLE',
    severity: 'HIGH',
    description: 'API boundaries assumed but not written. Interface contracts in developer heads. No contract tests.',
    scoringRules: {
      signals: [
        { signal: 'no_contract_tests', weight: 0.4, source_bonus: { testFile: 0.1 } },
        { signal: 'no_interface_definitions', weight: 0.3 },
        { signal: 'no_api_spec_doc', weight: 0.3, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-023',
    name: 'Contract Drift',
    gsProperty: 'EXECUTABLE',
    severity: 'HIGH',
    description: 'API docs describe behavior that does not match implementation. No automated check for spec-code drift.',
    scoringRules: {
      signals: [
        { signal: 'no_contract_tests', weight: 0.4, source_bonus: { testFile: 0.1 } },
        { signal: 'no_api_spec_doc', weight: 0.3, source_bonus: { spec: 0.1 } },
        { signal: 'no_executable_spec', weight: 0.3, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-024',
    name: 'Probe Absence',
    gsProperty: 'EXECUTABLE',
    severity: 'HIGH',
    description: 'No live system probes. Tests only run against mocks. No Hurl or equivalent against a running system.',
    scoringRules: {
      signals: [
        { signal: 'no_contract_tests', weight: 0.45, source_bonus: { testFile: 0.1 } },
        { signal: 'no_executable_spec', weight: 0.35, source_bonus: { spec: 0.1 } },
        { signal: 'no_e2e_tests', weight: 0.2, source_bonus: { testFile: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-025',
    name: 'Regression Blindness',
    gsProperty: 'DEFENDED',
    severity: 'HIGH',
    description: 'Fixes break previously working features. No regression fixtures. Bug recurs because root cause was not captured as a test.',
    scoringRules: {
      signals: [
        { signal: 'no_regression_fixtures', weight: 0.45, source_bonus: { testFile: 0.1 } },
        { signal: 'no_pre_commit_hooks', weight: 0.3 },
        { signal: 'no_ci_gate', weight: 0.25 },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-026',
    name: 'AI Hallucination Blindspot',
    gsProperty: 'VERIFIABLE',
    severity: 'HIGH',
    description: 'Dependencies on non-existent packages, subtle logic errors passing review. No AI-specific review checklist. Hallucinations merged to production.',
    scoringRules: {
      signals: [
        { signal: 'no_code_review_standards', weight: 0.5, source_bonus: { survey: 0.05 } },
        { signal: 'no_contract_tests', weight: 0.3, source_bonus: { testFile: 0.1 } },
        { signal: 'no_test_files', weight: 0.2, source_bonus: { testFile: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-027',
    name: 'Phase Collapse TDD',
    gsProperty: 'EXECUTABLE',
    severity: 'MEDIUM',
    description: 'AI writes test and implementation together. RED phase of TDD ceases to exist. Test suite becomes documentation, not verification.',
    scoringRules: {
      signals: [
        { signal: 'phase_collapse_signs', weight: 0.5, source_bonus: { survey: 0.05 } },
        { signal: 'no_test_files', weight: 0.3, source_bonus: { testFile: 0.1 } },
        { signal: 'no_ci_gate', weight: 0.2 },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // GATES
  {
    code: 'P-028',
    name: 'Unchecked Generation',
    gsProperty: 'DEFENDED',
    severity: 'CRITICAL',
    description: 'AI output accepted without running tests. No CI pipeline. Commits without passing test suite. Gate Erosion merged in.',
    scoringRules: {
      signals: [
        { signal: 'no_ci_gate', weight: 0.4 },
        { signal: 'no_pre_commit_hooks', weight: 0.35 },
        { signal: 'no_test_files', weight: 0.25, source_bonus: { testFile: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-029',
    name: 'No Code Review Culture',
    gsProperty: 'DEFENDED',
    severity: 'HIGH',
    description: 'PRs merged without meaningful review. No AI-specific review standards. AI-generated code carries security flaws that slip through.',
    scoringRules: {
      signals: [
        { signal: 'no_code_review_standards', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'no_pre_commit_hooks', weight: 0.25 },
        { signal: 'no_ci_gate', weight: 0.2 },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-030',
    name: 'DevOps Pipeline Fragility',
    gsProperty: 'DEFENDED',
    severity: 'HIGH',
    description: 'CI/CD pipelines breaking under increased AI-generated code volume. Infra misconfigs. No deployment documentation.',
    scoringRules: {
      signals: [
        { signal: 'no_ci_gate', weight: 0.4 },
        { signal: 'infra_misconfig_signals', weight: 0.35, source_bonus: { survey: 0.05 } },
        { signal: 'no_deployment_doc', weight: 0.25, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-031',
    name: 'Silent Upgrade Regression',
    gsProperty: 'DEFENDED',
    severity: 'MEDIUM',
    description: 'Model updates silently change AI output quality. No model version pinning. Previously working workflows suddenly produce worse output.',
    scoringRules: {
      signals: [
        { signal: 'no_model_version_pinning', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'no_regression_fixtures', weight: 0.45, source_bonus: { testFile: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // AI_QUALITY
  {
    code: 'P-032',
    name: 'AI Security Blindspot',
    gsProperty: 'DEFENDED',
    severity: 'CRITICAL',
    description: 'Sensitive data sent in prompts without policy. AI-generated code carries security flaws not caught before production.',
    scoringRules: {
      signals: [
        { signal: 'no_ai_security_policy', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'unauthorized_ai_tools', weight: 0.25, source_bonus: { survey: 0.05 } },
        { signal: 'no_code_review_standards', weight: 0.2, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-033',
    name: 'Confidence Inflation',
    gsProperty: 'VERIFIABLE',
    severity: 'HIGH',
    description: 'LLM returns percentage confidence as facts. No deterministic scoring engine. Evidence quality ignored. "AI said so" used as citation.',
    scoringRules: {
      signals: [
        { signal: 'llm_used_for_scoring', weight: 0.5, source_bonus: { survey: 0.05 } },
        { signal: 'no_deterministic_scoring', weight: 0.3 },
        { signal: 'no_test_files', weight: 0.2, source_bonus: { testFile: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-034',
    name: 'Shadow AI',
    gsProperty: 'DEFENDED',
    severity: 'HIGH',
    description: 'Team members use unauthorized AI tools without governance. Security, compliance, and consistency risks from uncontrolled AI usage.',
    scoringRules: {
      signals: [
        { signal: 'unauthorized_ai_tools', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'no_ai_rollout_plan', weight: 0.25, source_bonus: { survey: 0.05 } },
        { signal: 'no_team_ai_playbook', weight: 0.2, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-035',
    name: 'AI Productivity Paradox',
    gsProperty: 'VERIFIABLE',
    severity: 'HIGH',
    description: 'Developers feel faster individually, but organizational delivery velocity stays flat or declines. AI adds noise, not throughput.',
    scoringRules: {
      signals: [
        { signal: 'no_ai_measurement', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'no_tech_debt_tracking', weight: 0.45, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-036',
    name: 'Accountability Vacuum',
    gsProperty: 'DEFENDED',
    severity: 'HIGH',
    description: '"The AI generated it" is used to explain bugs. No ownership model for AI code. Whoever approves code owns it, but no policy enforces this.',
    scoringRules: {
      signals: [
        { signal: 'no_ai_security_policy', weight: 0.4, source_bonus: { survey: 0.05 } },
        { signal: 'no_code_review_standards', weight: 0.35, source_bonus: { survey: 0.05 } },
        { signal: 'no_ai_measurement', weight: 0.25, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-037',
    name: 'Trust Erosion Cycle',
    gsProperty: 'VERIFIABLE',
    severity: 'MEDIUM',
    description: 'Developer trust in AI output declines over time. AI fatigue shows up in team discussion. No metrics exist to validate or refute trust perceptions.',
    scoringRules: {
      signals: [
        { signal: 'no_ai_measurement', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'no_code_review_standards', weight: 0.45, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // AI_ADOPTION
  {
    code: 'P-038',
    name: 'Prompt Illiteracy',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'MEDIUM',
    description: 'Team uses AI superficially without prompt engineering skills. No shared prompt library. Benefits of AI tools are not realized.',
    scoringRules: {
      signals: [
        { signal: 'no_prompt_library', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'no_team_ai_playbook', weight: 0.45, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-039',
    name: 'Context Window Blindness',
    gsProperty: 'BOUNDED',
    severity: 'MEDIUM',
    description: 'Team is unaware AI silently truncates large files and wide contexts. Large artifacts are loaded without chunking strategy. Context degradation goes undetected.',
    scoringRules: {
      signals: [
        { signal: 'context_window_violations', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'no_team_ai_playbook', weight: 0.45, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-040',
    name: 'Uneven Adoption',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'MEDIUM',
    description: 'One or two AI-fluent teams surge ahead while others barely use the tools. No graduated rollout plan. Knowledge inequality and process inconsistency follow.',
    scoringRules: {
      signals: [
        { signal: 'no_team_ai_playbook', weight: 0.45, source_bonus: { survey: 0.05 } },
        { signal: 'no_ai_rollout_plan', weight: 0.55, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-041',
    name: 'Broken Context Anti-Pattern',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'MEDIUM',
    description: 'Wildly inconsistent code emerges from different AI personalities. No shared AI playbook. Each developer has their own workflow and context habits.',
    scoringRules: {
      signals: [
        { signal: 'no_team_ai_playbook', weight: 0.55, source_bonus: { survey: 0.05 } },
        { signal: 'inconsistent_naming', weight: 0.25, source_bonus: { survey: 0.05 } },
        { signal: 'no_navigation_root', weight: 0.2, source_bonus: { claudeMd: 0.15 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // CODE_HEALTH
  {
    code: 'P-042',
    name: 'AI-Accelerated Tech Debt',
    gsProperty: 'VERIFIABLE',
    severity: 'HIGH',
    description: 'AI-generated code introduces technical debt faster than the team can manage. Debt rate exceeds paydown rate.',
    scoringRules: {
      signals: [
        { signal: 'no_tech_debt_tracking', weight: 0.4, source_bonus: { survey: 0.05 } },
        { signal: 'no_duplication_gate', weight: 0.35 },
        { signal: 'no_dead_code_gate', weight: 0.25 },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },

  // OPERATIONS
  {
    code: 'P-043',
    name: 'Environment Opacity',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'MEDIUM',
    description: 'Env vars undocumented. No .env.example. New developers cannot onboard without tribal knowledge. AI cannot bootstrap local setup.',
    scoringRules: {
      signals: [
        { signal: 'no_env_example', weight: 0.5, source_bonus: { spec: 0.1 } },
        { signal: 'no_readme', weight: 0.5, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-044',
    name: 'Deployment Opacity',
    gsProperty: 'EXECUTABLE',
    severity: 'MEDIUM',
    description: 'No documented deployment process. Production differs from dev in unknown ways. No health probes. AI cannot generate valid deployment configs.',
    scoringRules: {
      signals: [
        { signal: 'no_deployment_doc', weight: 0.4, source_bonus: { spec: 0.1 } },
        { signal: 'no_env_example', weight: 0.35, source_bonus: { spec: 0.1 } },
        { signal: 'no_executable_spec', weight: 0.25, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-045',
    name: 'Skill Atrophy Syndrome',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'HIGH',
    description: 'Developers cannot debug or build without AI. Juniors cannot write basic code from scratch. Deep AI dependency grows without capability building.',
    scoringRules: {
      signals: [
        { signal: 'skill_atrophy_signs', weight: 0.6, source_bonus: { survey: 0.05 } },
        { signal: 'no_code_review_standards', weight: 0.4, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-046',
    name: 'ADR Absence',
    gsProperty: 'AUDITABLE',
    severity: 'MEDIUM',
    description: 'No Architecture Decision Records. Technology decisions remain undocumented. The team cannot explain why the current stack was chosen.',
    scoringRules: {
      signals: [
        { signal: 'no_adr_files', weight: 0.7, source_bonus: { adr: 0.15 } },
        { signal: 'no_decision_log', weight: 0.3, source_bonus: { spec: 0.1 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
  {
    code: 'P-047',
    name: 'Mandate Without Method',
    gsProperty: 'SELF_DESCRIBING',
    severity: 'MEDIUM',
    description: 'Leadership mandates AI use without giving teams a rollout plan, prompt patterns, or workflow standards. Adoption becomes performative and inconsistent.',
    scoringRules: {
      signals: [
        { signal: 'no_ai_rollout_plan', weight: 0.4, source_bonus: { survey: 0.05 } },
        { signal: 'no_prompt_library', weight: 0.35, source_bonus: { survey: 0.05 } },
        { signal: 'no_team_ai_playbook', weight: 0.25, source_bonus: { survey: 0.05 } },
      ],
      threshold_weak: 20,
      threshold_moderate: 40,
      threshold_strong: 65,
      threshold_corroborated: 80,
    },
  },
]
