import type { SurveyQuestion } from './types'

export const SURVEY_QUESTIONS: SurveyQuestion[] = [
  {
    questionKey: 'ai_session_context',
    questionText: 'When you start a new coding session with an AI assistant, how does it know about your project\'s conventions?',
    questionType: 'SINGLE_SELECT',
    options: [
      'It reads a documented navigation root (CLAUDE.md, AGENTS.md)',
      'I paste relevant context manually',
      'I start fresh and re-explain each session',
      'We don\'t use AI assistants for coding',
    ],
    signalKeys: ['no_navigation_root', 'no_session_protocol'],
    weight: 0.9,
    order: 1,
    isRequired: true,
    isFunnelVisible: true,
    section: 'ai_workflow',
  },
  {
    questionKey: 'spec_first_discipline',
    questionText: 'When building a new feature, at what point do you write the specification or design doc?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Before writing any code (spec-first)',
      'Roughly at the same time as the code',
      'After the code works, as documentation',
      'We don\'t write specs or design docs',
    ],
    signalKeys: ['spec_last_workflow', 'no_spec_document'],
    weight: 0.85,
    order: 2,
    isRequired: true,
    isFunnelVisible: true,
    section: 'spec_discipline',
  },
  {
    questionKey: 'ai_output_gate',
    questionText: 'When an AI assistant generates code, what happens before it\'s committed to your repo?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Full test suite runs + pre-commit hooks enforce gates',
      'I manually review and run some tests',
      'I review it but rarely run the test suite',
      'Committed immediately if it looks right',
    ],
    signalKeys: ['no_pre_commit_hooks', 'no_ci_gate'],
    weight: 0.85,
    order: 3,
    isRequired: true,
    isFunnelVisible: true,
    section: 'ai_workflow',
  },
  {
    questionKey: 'architectural_decisions',
    questionText: 'When your team makes a significant architectural decision (framework, DB, pattern), how is it documented?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Written as ADR files in the repository',
      'In a shared doc or wiki',
      'In Slack/tickets — searchable but informal',
      'It stays in the team\'s heads',
    ],
    signalKeys: ['no_adr_files', 'no_decision_log'],
    weight: 0.8,
    order: 4,
    isRequired: true,
    isFunnelVisible: false,
    section: 'change_governance',
  },
  {
    questionKey: 'has_coverage_gate',
    questionText: 'Does your CI pipeline fail if test coverage drops below a defined threshold?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Yes, enforced in CI (80%+ threshold)',
      'Yes, but below 50% threshold',
      'We track coverage but don\'t gate on it',
      'No CI pipeline or no test coverage tracking',
    ],
    signalKeys: ['no_ci_gate', 'no_coverage_config'],
    weight: 0.8,
    order: 5,
    isRequired: true,
    isFunnelVisible: false,
    section: 'quality_enforcement',
  },
  {
    questionKey: 'naming_consistency',
    questionText: 'How consistent is the naming of concepts across your codebase?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Very consistent — we have a documented domain vocabulary',
      'Mostly consistent, minor drift in older code',
      'Inconsistent — same concept has 2-3 different names',
      'No standards for naming',
    ],
    signalKeys: ['inconsistent_naming', 'no_domain_vocabulary'],
    weight: 0.7,
    order: 6,
    isRequired: false,
    isFunnelVisible: false,
    section: 'spec_discipline',
  },
  {
    questionKey: 'contract_tests',
    questionText: 'Do you have tests that run against your actual running API (not mocked)?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Yes — Hurl, Postman, or Playwright contract tests',
      'Some integration tests with real DB, mocked HTTP',
      'Unit tests only (everything mocked)',
      'No automated tests',
    ],
    signalKeys: ['no_contract_tests', 'no_e2e_tests'],
    weight: 0.75,
    order: 7,
    isRequired: false,
    isFunnelVisible: false,
    section: 'quality_enforcement',
  },
  {
    questionKey: 'layer_enforcement',
    questionText: 'Do you have automated checks preventing business logic from leaking into wrong layers?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Yes — dependency-cruiser, eslint-plugin-boundaries, or similar',
      'Code review catches it (manual)',
      'We try, but it slips through sometimes',
      'No layer enforcement',
    ],
    signalKeys: ['no_layer_enforcement', 'no_dependency_rules'],
    weight: 0.8,
    order: 8,
    isRequired: false,
    isFunnelVisible: false,
    section: 'quality_enforcement',
  },
  {
    questionKey: 'forbidden_patterns',
    questionText: 'Does your codebase have a documented list of explicitly prohibited patterns (with reasons)?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Yes — documented and enforced via linting rules',
      'Informal team knowledge (not written)',
      'No explicit list of prohibited patterns',
    ],
    signalKeys: ['no_forbidden_patterns'],
    weight: 0.7,
    order: 9,
    isRequired: false,
    isFunnelVisible: false,
    section: 'change_governance',
  },
  {
    questionKey: 'spec_update_discipline',
    questionText: 'When you change existing behavior, do you update the spec/design doc before or alongside the code?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Yes, always — spec is updated first or simultaneously',
      'Usually, but sometimes we forget',
      'Rarely — spec is perpetually behind the code',
      'We don\'t have a spec to update',
    ],
    signalKeys: ['no_spec_document', 'spec_last_workflow'],
    weight: 0.75,
    order: 10,
    isRequired: false,
    isFunnelVisible: false,
    section: 'spec_discipline',
  },
  {
    questionKey: 'session_manifests',
    questionText: 'Do your AI coding sessions start with a written goal, scope, and definition of done?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Yes — we use a session manifest every time',
      'Sometimes — for bigger tasks',
      'No — we just start prompting',
    ],
    signalKeys: ['no_session_protocol'],
    weight: 0.8,
    order: 11,
    isRequired: false,
    isFunnelVisible: false,
    section: 'ai_workflow',
  },
  {
    questionKey: 'commit_message_quality',
    questionText: 'What do your git commit messages typically look like?',
    questionType: 'SINGLE_SELECT',
    options: [
      'Conventional Commits format (feat:, fix:, refactor:)',
      'Descriptive sentences but no standard format',
      'Brief: "fix", "update", "tweak", "wip"',
      'We don\'t pay attention to commit messages',
    ],
    signalKeys: ['no_conventional_commits'],
    weight: 0.6,
    order: 12,
    isRequired: false,
    isFunnelVisible: false,
    section: 'change_governance',
  },
]
