import type { Remedy } from './types'

export const REMEDIES: Remedy[] = [
  {
    code: 'R-001', name: 'Navigation Root (CLAUDE.md)', remediationType: 'practice',
    effort: 'low', impact: 'high',
    gsProperties: ['SELF_DESCRIBING', 'BOUNDED'],
    pathologyCodes: ['P-001', 'P-002', 'P-004', 'P-009', 'P-014', 'P-019', 'P-027'],
    description: 'Create a CLAUDE.md at project root that every AI session reads first. Contains project overview, key file index, domain vocabulary, and links to spec sections and ADRs.',
    steps: [
      'Create CLAUDE.md at project root',
      'Add: project overview (3-5 sentences)',
      'Add: key file index with paths',
      'Add: domain vocabulary table (term → definition)',
      'Add: links to spec, ADRs, session manifest',
      'Add: "Read this first every session" instruction',
    ],
  },
  {
    code: 'R-002', name: 'ADR Practice', remediationType: 'practice',
    effort: 'low', impact: 'high',
    gsProperties: ['AUDITABLE'],
    pathologyCodes: ['P-004', 'P-007', 'P-011', 'P-015'],
    description: 'Establish Architecture Decision Records for every significant technical choice. Each ADR records: context, decision, alternatives, consequences.',
    steps: [
      'Create docs/adrs/ directory',
      'Write ADR-000 (template + process)',
      'Retroactively write ADRs for top 3 existing decisions',
      'Add ADR creation to session manifest checklist',
    ],
  },
  {
    code: 'R-003', name: 'Conventional Commits', remediationType: 'protocol',
    effort: 'low', impact: 'medium',
    gsProperties: ['AUDITABLE'],
    pathologyCodes: ['P-007', 'P-015'],
    description: 'Adopt Conventional Commits (feat:, fix:, chore:, docs:, refactor:). Every commit references a spec session.',
    steps: [
      'Install commitlint + husky',
      'Configure .commitlintrc.json',
      'Add .gitmessage template',
      'Train team on format: type(scope): description [session-id]',
    ],
  },
  {
    code: 'R-004', name: 'TDD Protocol (RED→GREEN→REFACTOR)', remediationType: 'protocol',
    effort: 'medium', impact: 'high',
    gsProperties: ['VERIFIABLE'],
    pathologyCodes: ['P-006', 'P-010', 'P-013', 'P-028'],
    description: 'Enforce test-driven development. Every new behavior starts with a failing test. Coverage gate at 80% enforced in CI.',
    steps: [
      'Configure test runner with coverage thresholds (80%)',
      'Add coverage gate to CI pipeline',
      'Add to CLAUDE.md: "Write test first, then implementation"',
      'Add checklist item: "Tests pass before committing"',
    ],
  },
  {
    code: 'R-005', name: 'Hurl Contract Tests', remediationType: 'tool',
    effort: 'medium', impact: 'high',
    gsProperties: ['EXECUTABLE', 'VERIFIABLE'],
    pathologyCodes: ['P-003', 'P-010', 'P-012', 'P-023'],
    description: 'Write Hurl (.hurl) files as executable API contracts. Each endpoint gets a probe that tests real behavior against a running server.',
    steps: [
      'Install Hurl CLI (hurl.dev)',
      'Create tests/hurl/ directory',
      'Write .hurl file for each API endpoint',
      'Include auth, request body, response assertions',
      'Add hurl probe step to CI pipeline',
    ],
  },
  {
    code: 'R-006', name: 'Layer Enforcement (depcruise)', remediationType: 'gate',
    effort: 'low', impact: 'high',
    gsProperties: ['DEFENDED', 'COMPOSABLE'],
    pathologyCodes: ['P-001', 'P-008', 'P-016', 'P-025'],
    description: 'Use dependency-cruiser to enforce architectural layers. Prevent domain layer from importing infrastructure. Run as pre-commit hook and CI gate.',
    steps: [
      'Install dependency-cruiser',
      'Configure .dependency-cruiser.cjs with layer rules',
      'Define forbidden: domain/* → infrastructure/*',
      'Define forbidden: routes/* → prisma/*',
      'Add to pre-commit hooks and CI',
    ],
  },
  {
    code: 'R-007', name: 'Dead Code Elimination (knip)', remediationType: 'gate',
    effort: 'low', impact: 'medium',
    gsProperties: ['BOUNDED'],
    pathologyCodes: ['P-018'],
    description: 'Use knip to detect unused exports, files, and dependencies. Run weekly.',
    steps: [
      'Install knip',
      'Configure knip.json',
      'Run: npx knip --reporter compact',
      'Remove flagged dead code',
      'Add to weekly CI schedule',
    ],
  },
  {
    code: 'R-008', name: 'Duplication Gate (jscpd)', remediationType: 'gate',
    effort: 'low', impact: 'medium',
    gsProperties: ['COMPOSABLE'],
    pathologyCodes: ['P-017'],
    description: 'Use jscpd to detect code duplication above 3%. Gate fails CI if threshold exceeded.',
    steps: [
      'Install jscpd',
      'Configure .jscpd.json with threshold: 3',
      'Run: npx jscpd src/',
      'Extract duplicated logic to shared utilities',
      'Add to CI pipeline',
    ],
  },
  {
    code: 'R-009', name: 'Bounded Spec Sections', remediationType: 'practice',
    effort: 'medium', impact: 'high',
    gsProperties: ['BOUNDED'],
    pathologyCodes: ['P-005', 'P-015', 'P-021'],
    description: 'Split monolithic spec into bounded sections of max 500 lines each. Each section independently loadable.',
    steps: [
      'Audit current spec for size (>200KB is pathological)',
      'Split into numbered sections: 01-overview, 02-domain, etc.',
      'Create spec-map.md with decision tree',
      'Update CLAUDE.md to reference spec-map.md',
      'Set section size limit: max 500 lines',
    ],
  },
  {
    code: 'R-010', name: 'Spec Index + Decision Tree', remediationType: 'practice',
    effort: 'low', impact: 'high',
    gsProperties: ['BOUNDED', 'SELF_DESCRIBING'],
    pathologyCodes: ['P-005', 'P-021', 'P-027'],
    description: 'Create a spec-map.md that routes AI sessions to the right section. Organized as a decision tree: "Working on auth? → Load section 05."',
    steps: [
      'List all spec sections with purpose',
      'Write decision tree: IF working on X THEN read section Y',
      'Add to CLAUDE.md as primary navigation',
      'Test: verify AI uses only relevant sections',
    ],
  },
  {
    code: 'R-011', name: 'Mutation Testing', remediationType: 'tool',
    effort: 'medium', impact: 'high',
    gsProperties: ['VERIFIABLE'],
    pathologyCodes: ['P-006', 'P-010'],
    description: 'Run mutation testing to verify tests actually catch bugs. Target: >70% mutation score.',
    steps: [
      'Install @vitest/coverage-v8 or Stryker',
      'Configure mutation testing thresholds',
      'Run coverage report',
      'Target: >70% mutation score',
      'Add to weekly CI schedule',
    ],
  },
  {
    code: 'R-012', name: 'Domain Vocabulary Glossary', remediationType: 'practice',
    effort: 'low', impact: 'medium',
    gsProperties: ['SELF_DESCRIBING'],
    pathologyCodes: ['P-001', 'P-009', 'P-022'],
    description: 'Maintain a living glossary of all domain terms. Every concept has exactly one canonical name.',
    steps: [
      'Create docs/vocabulary.md',
      'List all domain entities with definitions',
      'Define canonical names (one name per concept)',
      'Add to CLAUDE.md: "See vocabulary.md for canonical names"',
      'Update with each new domain concept',
    ],
  },
  {
    code: 'R-013', name: 'Forbidden Patterns Catalog', remediationType: 'practice',
    effort: 'medium', impact: 'high',
    gsProperties: ['DEFENDED'],
    pathologyCodes: ['P-008', 'P-013', 'P-014', 'P-020'],
    description: 'Document patterns explicitly forbidden in this codebase, with reason for each prohibition. AI sessions check this list before generating code.',
    steps: [
      'Create docs/standards/forbidden-patterns.md',
      'List: any, console.log, direct DB in routes, etc.',
      'For each: name, reason, correct alternative',
      'Reference from CLAUDE.md',
      'Add ESLint rules to enforce mechanically',
    ],
  },
  {
    code: 'R-014', name: 'Pre-commit Gate Stack', remediationType: 'gate',
    effort: 'medium', impact: 'high',
    gsProperties: ['DEFENDED'],
    pathologyCodes: ['P-013', 'P-020', 'P-028'],
    description: 'Install pre-commit hooks that run: lint, typecheck, tests, forbidden pattern check, and layer enforcement. No commit passes without all gates green.',
    steps: [
      'Install husky + lint-staged',
      'Configure: eslint → tsc → vitest → depcruise',
      'Add forbidden pattern grep checks',
      'Document skip procedure (requires written justification)',
    ],
  },
  {
    code: 'R-015', name: 'Session Manifest Discipline', remediationType: 'protocol',
    effort: 'low', impact: 'high',
    gsProperties: ['AUDITABLE', 'SELF_DESCRIBING'],
    pathologyCodes: ['P-002', 'P-014', 'P-015'],
    description: 'Begin every AI session with a session manifest: goal, files to touch, tests to run, definition of done.',
    steps: [
      'Create session manifest template',
      'Add to CLAUDE.md: "Start every session by filling session manifest"',
      'Include: goal, scope, files, tests, done criteria',
      'After session: record actual changes and decisions',
      'Archive manifests in docs/sessions/',
    ],
  },
  {
    code: 'R-016', name: 'Hybrid Scoring Engine Pattern', remediationType: 'practice',
    effort: 'high', impact: 'high',
    gsProperties: ['VERIFIABLE', 'EXECUTABLE'],
    pathologyCodes: ['P-006', 'P-026'],
    description: 'Replace LLM confidence percentages with a deterministic scoring engine that combines signal weights, evidence source bonuses, and corroboration factors.',
    steps: [
      'Define signal catalog (binary: present or absent)',
      'Assign weights per signal per pathology',
      'Define source bonuses (code > survey > LLM assertion)',
      'Implement scoring engine as pure function',
      'Test: same inputs always produce same score',
    ],
  },
  {
    code: 'R-017', name: 'Executable Behavioral Probes', remediationType: 'practice',
    effort: 'medium', impact: 'high',
    gsProperties: ['EXECUTABLE'],
    pathologyCodes: ['P-012', 'P-023', 'P-029'],
    description: 'Write probes that test real system behavior. Run against running system (local or staging). Prove system behaves as specified.',
    steps: [
      'Write Hurl or Playwright probes for critical paths',
      'Include: happy path, auth failure, validation error',
      'Run probes against staging before production deploy',
      'Add probe results to release checklist',
    ],
  },
  {
    code: 'R-018', name: 'Interface-based Dependency Injection', remediationType: 'practice',
    effort: 'medium', impact: 'high',
    gsProperties: ['COMPOSABLE'],
    pathologyCodes: ['P-003', 'P-008', 'P-016', 'P-025'],
    description: 'Define all external dependencies as interfaces (ports). Implementations injected at composition root. Domain layer never imports infrastructure directly.',
    steps: [
      'Create domain/ports/ directory',
      'Define repository interfaces for each aggregate',
      'Create infrastructure/adapters/ with implementations',
      'Wire DI at composition root (app.ts or main.ts)',
      'Add layer enforcement gate',
    ],
  },
  {
    code: 'R-019', name: 'Screaming Architecture', remediationType: 'practice',
    effort: 'low', impact: 'medium',
    gsProperties: ['SELF_DESCRIBING'],
    pathologyCodes: ['P-001', 'P-009', 'P-027'],
    description: 'Directory structure screams the domain, not the framework. Top-level directories are domain concepts, not technical layers.',
    steps: [
      'Rename src/ subdirectories to domain names',
      'Group files by feature/domain, not by type',
      'Update imports after rename',
      'Update CLAUDE.md directory index',
    ],
  },
  {
    code: 'R-020', name: 'Specification-First Protocol', remediationType: 'protocol',
    effort: 'high', impact: 'critical',
    gsProperties: ['SELF_DESCRIBING', 'AUDITABLE'],
    pathologyCodes: ['P-004', 'P-013', 'P-015', 'P-021', 'P-024'],
    description: 'No code written before the spec section for that feature exists. The spec is the contract; code is the implementation.',
    steps: [
      'Add to session manifest: "Read spec section before writing code"',
      'Add to CLAUDE.md: "Spec-first is mandatory"',
      'Create spec section template',
      'Add spec review to PR checklist',
      'Gate: PR description must reference spec section',
    ],
  },
]
