import type { Prisma } from '@prisma/client'

export const remedies: Prisma.RemedyKnowledgeCreateInput[] = [
  {
    code: 'R-001',
    name: 'Navigation Root (CLAUDE.md)',
    description: 'Create a CLAUDE.md or equivalent navigation root that loads at the start of every AI session. It must contain: project overview, key file index, domain vocabulary, and links to spec sections, ADRs, and session protocols. The AI reads this first every session.',
    remediationType: 'practice',
    effort: 'low',
    impact: 'high',
    gsProperties: ['SELF_DESCRIBING', 'BOUNDED'],
    steps: [
      'Create CLAUDE.md at project root',
      'Add project overview (3-5 sentences)',
      'Add key file index with absolute paths',
      'Add domain vocabulary table (term → definition)',
      'Add links to spec sections, ADRs, session manifest',
      'Add "Read this first" instructions for AI sessions',
      'Test: start a new AI session and verify CLAUDE.md is loaded',
    ],
  },
  {
    code: 'R-002',
    name: 'ADR Practice',
    description: 'Establish Architecture Decision Records for every significant technical choice. Each ADR records: context, decision, alternatives considered, consequences. ADRs are immutable once decided — superseded by new ADRs.',
    remediationType: 'practice',
    effort: 'low',
    impact: 'high',
    gsProperties: ['AUDITABLE'],
    steps: [
      'Create docs/adrs/ directory',
      'Write ADR-000 (template + process explanation)',
      'Retroactively write ADRs for top 3 existing decisions',
      'Add ADR creation to session manifest checklist',
      'Reference ADRs from CLAUDE.md',
    ],
  },
  {
    code: 'R-003',
    name: 'Conventional Commits',
    description: 'Adopt Conventional Commits standard (feat:, fix:, chore:, docs:, refactor:) for all commits. Every commit references a spec session or ticket. This creates an auditable history of decisions.',
    remediationType: 'protocol',
    effort: 'low',
    impact: 'medium',
    gsProperties: ['AUDITABLE'],
    steps: [
      'Install commitlint + husky pre-commit hook',
      'Configure .commitlintrc.json with conventional-commits ruleset',
      'Add commit template to .gitmessage',
      'Train team on format: type(scope): description [RM-xxx]',
    ],
  },
  {
    code: 'R-004',
    name: 'TDD Protocol (RED→GREEN→REFACTOR)',
    description: 'Enforce test-driven development as the default workflow. Every new behavior starts with a failing test. AI sessions must run tests before committing. Coverage gate enforced at 80%.',
    remediationType: 'protocol',
    effort: 'medium',
    impact: 'high',
    gsProperties: ['VERIFIABLE'],
    steps: [
      'Configure test runner (Vitest/Jest) with coverage thresholds',
      'Add coverage gate to CI pipeline',
      'Add to CLAUDE.md: "Write test first, then implementation"',
      'Create session manifest checklist item: "Tests pass before committing"',
      'Enable pre-commit hook to run tests',
    ],
  },
  {
    code: 'R-005',
    name: 'Hurl Contract Tests',
    description: 'Write Hurl (.hurl) files as executable API contracts. Each endpoint gets a probe file that tests real behavior against a running server. These serve as both documentation and regression tests.',
    remediationType: 'tool',
    effort: 'medium',
    impact: 'high',
    gsProperties: ['EXECUTABLE', 'VERIFIABLE'],
    steps: [
      'Install Hurl CLI',
      'Create tests/hurl/ directory',
      'Write .hurl file for each API endpoint',
      'Include auth headers, request body, response assertions',
      'Add hurl probe step to CI pipeline',
      'Document probe URLs in CLAUDE.md',
    ],
  },
  {
    code: 'R-006',
    name: 'Layer Enforcement (depcruise)',
    description: 'Use dependency-cruiser to enforce architectural layers. Define rules that prevent domain layer from importing infrastructure layer. Run as pre-commit hook and CI gate.',
    remediationType: 'gate',
    effort: 'low',
    impact: 'high',
    gsProperties: ['DEFENDED', 'COMPOSABLE'],
    steps: [
      'Install dependency-cruiser',
      'Configure .dependency-cruiser.cjs with layer rules',
      'Define forbidden: domain/* → infrastructure/*',
      'Define forbidden: routes/* → prisma/*',
      'Add to pre-commit hooks',
      'Add to CI pipeline',
    ],
  },
  {
    code: 'R-007',
    name: 'Dead Code Elimination (knip)',
    description: 'Use knip to detect and remove unused exports, files, and dependencies. Run weekly as a scheduled CI job. Never allow dead code to accumulate for more than one sprint.',
    remediationType: 'gate',
    effort: 'low',
    impact: 'medium',
    gsProperties: ['BOUNDED'],
    steps: [
      'Install knip',
      'Configure knip.json to match project structure',
      'Run: npx knip --reporter compact',
      'Review and remove flagged dead code',
      'Add to weekly CI schedule',
    ],
  },
  {
    code: 'R-008',
    name: 'Duplication Gate (jscpd)',
    description: 'Use jscpd to detect code duplication above 3%. When duplication detected, extract shared abstraction before proceeding. Gate fails CI if duplication exceeds threshold.',
    remediationType: 'gate',
    effort: 'low',
    impact: 'medium',
    gsProperties: ['COMPOSABLE'],
    steps: [
      'Install jscpd',
      'Configure .jscpd.json with threshold: 3',
      'Run: npx jscpd src/',
      'Extract duplicated logic to shared utilities',
      'Add to CI pipeline',
    ],
  },
  {
    code: 'R-009',
    name: 'Bounded Spec Sections',
    description: 'Split monolithic spec into bounded sections of max 500 lines each. Each section is independently loadable. A spec-map.md provides routing between sections. AI loads only the relevant section.',
    remediationType: 'practice',
    effort: 'medium',
    impact: 'high',
    gsProperties: ['BOUNDED'],
    steps: [
      'Audit current spec for size (> 200KB is pathological)',
      'Split into numbered sections: 01-overview, 02-domain, etc.',
      'Create spec-map.md with decision tree for routing',
      'Update CLAUDE.md to reference spec-map.md',
      'Set section size limit in CLAUDE.md: max 500 lines',
    ],
  },
  {
    code: 'R-010',
    name: 'Spec Index + Decision Tree',
    description: 'Create a spec-map.md that routes AI sessions to the right spec section. Organized as a decision tree: "Working on auth? → Load section 05. Working on payments? → Load section 09." Prevents full-spec loading.',
    remediationType: 'practice',
    effort: 'low',
    impact: 'high',
    gsProperties: ['BOUNDED', 'SELF_DESCRIBING'],
    steps: [
      'List all spec sections with purpose',
      'Write decision tree: IF working on X THEN read section Y',
      'Add to CLAUDE.md as primary navigation',
      'Test: verify AI uses only relevant sections in sessions',
    ],
  },
  {
    code: 'R-011',
    name: 'Mutation Testing (Stryker/Vitest)',
    description: 'Run mutation testing to verify tests actually catch bugs, not just execute code. A test suite that passes mutation testing proves it would catch real regressions.',
    remediationType: 'tool',
    effort: 'medium',
    impact: 'high',
    gsProperties: ['VERIFIABLE'],
    steps: [
      'Install @vitest/coverage-v8 or Stryker',
      'Configure mutation testing thresholds',
      'Run: npx stryker run or vitest --coverage',
      'Target: >70% mutation score',
      'Add to weekly CI schedule',
    ],
  },
  {
    code: 'R-012',
    name: 'Domain Vocabulary Glossary',
    description: 'Maintain a living glossary of all domain terms with canonical definitions. Every concept has exactly one name used consistently across code, docs, and AI prompts.',
    remediationType: 'practice',
    effort: 'low',
    impact: 'medium',
    gsProperties: ['SELF_DESCRIBING'],
    steps: [
      'Create docs/vocabulary.md',
      'List all domain entities with definitions',
      'Define canonical names (e.g., "User" not "Member" or "Account")',
      'Add to CLAUDE.md: "See vocabulary.md for canonical names"',
      'Update with each new domain concept introduced',
    ],
  },
  {
    code: 'R-013',
    name: 'Forbidden Patterns Catalog',
    description: 'Maintain a documented list of patterns that are explicitly forbidden in this codebase, with the reason for each prohibition. AI sessions must check this list before generating code.',
    remediationType: 'practice',
    effort: 'medium',
    impact: 'high',
    gsProperties: ['DEFENDED'],
    steps: [
      'Create docs/standards/forbidden-patterns.md',
      'List: any, console.log, direct DB in routes, etc.',
      'For each: name, reason, correct alternative',
      'Reference from CLAUDE.md: "Check forbidden-patterns.md first"',
      'Add ESLint rules to enforce mechanically where possible',
    ],
  },
  {
    code: 'R-014',
    name: 'Pre-commit Gate Stack',
    description: 'Install a pre-commit hook stack that runs: lint, typecheck, tests, forbidden pattern check, and layer enforcement. No commit passes without all gates green.',
    remediationType: 'gate',
    effort: 'medium',
    impact: 'high',
    gsProperties: ['DEFENDED'],
    steps: [
      'Install husky + lint-staged',
      'Configure: eslint → tsc → vitest → depcruise',
      'Add forbidden pattern grep checks',
      'Document skip procedure (requires written justification)',
      'Add gate list to CLAUDE.md',
    ],
  },
  {
    code: 'R-015',
    name: 'Session Manifest Discipline',
    description: 'Begin every AI session by writing a session manifest: goal, files to touch, tests to run, definition of done. End every session by updating the manifest with actual changes and any new decisions.',
    remediationType: 'protocol',
    effort: 'low',
    impact: 'high',
    gsProperties: ['AUDITABLE', 'SELF_DESCRIBING'],
    steps: [
      'Create session manifest template',
      'Add to CLAUDE.md: "Start every session by filling session manifest"',
      'Include: goal, scope, files, tests, done criteria',
      'After session: record actual changes, decisions, debt created',
      'Archive manifests in docs/sessions/',
    ],
  },
  {
    code: 'R-016',
    name: 'Hybrid Scoring Engine Pattern',
    description: 'Replace LLM confidence percentages with a deterministic scoring engine that combines: signal weights, evidence source bonuses, and corroboration factors. The LLM extracts signals; the engine scores.',
    remediationType: 'practice',
    effort: 'high',
    impact: 'high',
    gsProperties: ['VERIFIABLE', 'EXECUTABLE'],
    steps: [
      'Define signal catalog (binary: present or absent)',
      'Assign weights per signal per pathology',
      'Define source bonuses (code > survey > LLM assertion)',
      'Implement scoring engine as pure function',
      'Add corroboration factor for multi-source evidence',
      'Test: same inputs always produce same score',
    ],
  },
  {
    code: 'R-017',
    name: 'Executable Behavioral Probes',
    description: 'Write probes that test real system behavior, not mocks. These run against the running system (local or staging) and prove the system behaves as specified — not just that it compiles.',
    remediationType: 'practice',
    effort: 'medium',
    impact: 'high',
    gsProperties: ['EXECUTABLE'],
    steps: [
      'Write Hurl or Playwright probes for critical paths',
      'Include: happy path, auth failure, validation error',
      'Run probes against staging before production deploy',
      'Add probe results to release checklist',
    ],
  },
  {
    code: 'R-018',
    name: 'Interface-based Dependency Injection',
    description: 'Define all external dependencies as interfaces (ports). Implementations (adapters) are injected at composition root. Domain layer never imports infrastructure directly.',
    remediationType: 'practice',
    effort: 'medium',
    impact: 'high',
    gsProperties: ['COMPOSABLE'],
    steps: [
      'Create domain/ports/ directory',
      'Define repository interfaces for each aggregate',
      'Create infrastructure/adapters/ with implementations',
      'Wire DI at app.ts or main.ts (composition root)',
      'Add layer enforcement gate to prevent domain → infra imports',
    ],
  },
  {
    code: 'R-019',
    name: 'Screaming Architecture',
    description: 'Directory structure should scream the domain, not the framework. Top-level directories are domain concepts (assessment, project, report), not technical layers (controllers, services, models).',
    remediationType: 'practice',
    effort: 'low',
    impact: 'medium',
    gsProperties: ['SELF_DESCRIBING'],
    steps: [
      'Rename src/ subdirectories from framework names to domain names',
      'Group files by feature/domain, not by type',
      'Update imports after rename',
      'Update CLAUDE.md directory index',
      'Update spec to document new structure',
    ],
  },
  {
    code: 'R-020',
    name: 'Specification-First Protocol',
    description: 'Enforce that no code is written before the spec section for that feature is created or updated. The spec is the contract; code is the implementation. AI sessions begin by reading the relevant spec section.',
    remediationType: 'protocol',
    effort: 'high',
    impact: 'critical',
    gsProperties: ['SELF_DESCRIBING', 'AUDITABLE'],
    steps: [
      'Add to session manifest: "Read spec section before writing code"',
      'Add to CLAUDE.md: "Spec-first is mandatory"',
      'Create spec section template (purpose, behavior, acceptance criteria)',
      'Add spec review to PR checklist',
      'Gate: PR description must reference spec section',
    ],
  },
]
